import { describe, expect, it } from 'vitest';
import type { StreamDetails } from '../shared/contracts';
import { resolvePlaybackSelection } from './playback-selection';

const details: StreamDetails = {
  serviceId: 0,
  url: 'https://example.test/watch',
  name: 'Example',
  duration: 120,
  streamType: 'VIDEO_STREAM',
  videoStreams: [
    { id: 'combined', url: 'https://example.test/combined', resolution: '720p' },
    { id: 'video-only', url: 'https://example.test/video', resolution: '1080p', videoOnly: true,
      audioTrackId: 'original' },
  ],
  audioStreams: [
    { id: 'dubbed', url: 'https://example.test/dubbed', audioTrackId: 'dubbed' },
    { id: 'original', url: 'https://example.test/original', audioTrackId: 'original' },
  ],
  subtitles: [
    { id: 'en', url: 'https://example.test/en.vtt', languageTag: 'en', displayLanguage: 'English',
      autoGenerated: false },
  ],
  relatedItems: [],
  sponsorBlockSegments: [],
};

describe('embedded playback selection', () => {
  it('uses a combined stream without an extra audio track in automatic mode', () => {
    expect(resolvePlaybackSelection(details, 'auto', 'auto', 'none')).toMatchObject({
      source: 'https://example.test/combined',
      video: details.videoStreams[0],
      audio: undefined,
      subtitle: undefined,
    });
  });

  it('pairs a video-only stream with its matching audio track', () => {
    expect(resolvePlaybackSelection(details, '1', 'auto', 'none')).toMatchObject({
      source: 'https://example.test/video',
      video: details.videoStreams[1],
      audio: details.audioStreams[1],
    });
  });

  it('keeps explicit audio and caption choices while changing video quality', () => {
    expect(resolvePlaybackSelection(details, '1', '0', '0')).toMatchObject({
      audio: details.audioStreams[0],
      subtitle: details.subtitles[0],
    });
  });

  it('uses an adaptive manifest for automatic playback when available', () => {
    expect(resolvePlaybackSelection({ ...details, hlsUrl: 'https://example.test/master.m3u8' },
      'auto', 'auto', 'none')).toMatchObject({
      source: 'https://example.test/master.m3u8',
      video: undefined,
    });
  });
});
