import { describe, expect, it } from 'vitest';
import {
  defaultDesktopSettings, type StreamDetails, type StreamVariant, type SubtitleVariant,
} from '../shared/contracts';
import {
  channelProfileKey, preferredAudioIndex, preferredSubtitleIndex, preferredVideoIndex,
  updatedChannelProfile,
} from './stream-preferences';

const details: StreamDetails = {
  serviceId: 0, url: 'https://example.test/watch', name: 'Example', duration: 10, streamType: 'VIDEO_STREAM',
  videoStreams: [
    { id: 'low', url: 'https://example.test/low', resolution: '480p', format: 'MPEG-4' },
    { id: 'webm', url: 'https://example.test/high', resolution: '720p60', format: 'WebM' },
    { id: 'mp4', url: 'https://example.test/preferred', resolution: '720p60', format: 'MPEG-4' },
  ],
  audioStreams: [
    { id: 'dubbed', url: 'https://example.test/dubbed', format: 'M4A', audioTrackType: 'DUBBED' },
    { id: 'original', url: 'https://example.test/original', format: 'WebM', audioTrackType: 'ORIGINAL' },
    { id: 'descriptive', url: 'https://example.test/descriptive', format: 'M4A', audioTrackType: 'DESCRIPTIVE' },
  ],
  subtitles: [],
  relatedItems: [],
  chapters: [],
  previewFrames: [],
  sponsorBlockSegments: [],
};

function streamDetails(patch: Partial<StreamDetails>): StreamDetails {
  return { ...details, ...patch };
}

function video(resolution: string, format: string): StreamVariant {
  return { id: `${resolution}:${format}`, url: `https://example.test/${resolution}/${format}`, resolution, format };
}

function audio(audioTrackId: string, audioLocale: string): StreamVariant {
  return { id: audioTrackId, url: `https://example.test/audio/${audioTrackId}`, audioTrackId, audioLocale };
}

function subtitle(languageTag: string): SubtitleVariant {
  return { id: languageTag, url: `https://example.test/subtitle/${languageTag}`, languageTag,
    displayLanguage: languageTag, autoGenerated: false };
}

describe('desktop stream preferences', () => {
  it('prefers the configured resolution and format', () => {
    expect(preferredVideoIndex(details, defaultDesktopSettings)).toBe(2);
  });

  it('prefers descriptive audio when requested', () => {
    expect(preferredAudioIndex(details, { ...defaultDesktopSettings, preferDescriptiveAudio: true })).toBe(2);
  });

  it('uses the original audio preference before the format preference', () => {
    expect(preferredAudioIndex(details, defaultDesktopSettings)).toBe(1);
  });
});

describe('channel playback profiles', () => {
  it('prefers saved channel tracks over global defaults', () => {
    const details = streamDetails({
      uploaderUrl: 'https://example.com/channel/1',
      videoStreams: [video('720p', 'MPEG_4'), video('1080p', 'WEBM')],
      audioStreams: [audio('original', 'en-US'), audio('dubbed', 'ar-LB')],
      subtitles: [subtitle('en-US'), subtitle('ar-LB')],
    });
    const key = channelProfileKey(details)!;
    const settings = { ...defaultDesktopSettings, channelPlaybackProfiles: {
      [key]: { videoResolution: '1080p', videoFormat: 'WEBM', audioTrackId: 'dubbed',
        subtitleLanguageTag: 'ar-LB', updatedAt: 1 },
    } };
    expect(preferredVideoIndex(details, settings)).toBe(1);
    expect(preferredAudioIndex(details, settings)).toBe(1);
    expect(preferredSubtitleIndex(details, settings)).toBe(1);
  });

  it('updates a bounded profile without discarding other channels', () => {
    const details = streamDetails({ uploaderName: 'Channel' });
    const profiles = updatedChannelProfile(details, defaultDesktopSettings, { speed: 1.5 });
    expect(profiles?.['0:Channel']).toMatchObject({ speed: 1.5 });
  });
});
