export type BackendMethod =
  | 'health'
  | 'services.list'
  | 'search'
  | 'feed.subscriptions'
  | 'stream.resolve'
  | 'stream.comments'
  | 'channel.resolve'
  | 'library.summary'
  | 'library.subscriptions.list'
  | 'library.subscriptions.save'
  | 'library.subscriptions.refresh-metadata'
  | 'library.subscriptions.delete'
  | 'library.playlists.list'
  | 'library.playlists.create'
  | 'library.playlists.rename'
  | 'library.playlists.delete'
  | 'library.playlists.items'
  | 'library.playlists.add-item'
  | 'library.playlists.delete-item'
  | 'library.history.list'
  | 'library.history.record'
  | 'library.history.delete'
  | 'library.history.clear'
  | 'library.playback-state.list'
  | 'library.playback-state.save'
  | 'library.search-history.list'
  | 'library.search-history.record'
  | 'library.search-history.delete'
  | 'library.search-history.clear'
  | 'library.learning.list'
  | 'library.learning.save'
  | 'library.learning.delete'
  | 'library.downloads.record'
  | 'sync.status'
  | 'sync.invitation'
  | 'sync.pair'
  | 'sync.policy.update'
  | 'sync.runs.list'
  | 'sync.run'
  | 'backup.export'
  | 'backup.inspect'
  | 'backup.restore'
  | 'subscriptions.import'
  | 'subscriptions.export';

export interface ServiceSummary {
  id: number;
  name: string;
  capabilities: string[];
}

export interface SearchItem {
  type: string;
  serviceId: number;
  url: string;
  name: string;
  thumbnailUrl?: string;
  uploaderName?: string;
  uploaderUrl?: string;
  uploaderAvatarUrl?: string;
  duration?: number;
  viewCount?: number | null;
  publishedAt?: number | null;
  textualUploadDate?: string;
  streamType?: string;
  shortForm?: boolean;
}

export interface SubscriptionFeed {
  items: SearchItem[];
  totalChannels: number;
  failedChannels: number;
  refreshedAt: number;
}

export interface PlaybackState {
  serviceId: number;
  url: string;
  positionMillis: number;
  updatedAt?: number;
}

export interface StreamVariant {
  id: string;
  url: string;
  format?: string;
  deliveryMethod?: string;
  resolution?: string;
  bitrate?: number;
  videoOnly?: boolean;
  codec?: string;
  audioTrackId?: string;
  audioTrackName?: string;
  audioLocale?: string;
  audioTrackType?: 'ORIGINAL' | 'DUBBED' | 'DESCRIPTIVE' | 'SECONDARY';
}

export interface SubtitleVariant {
  id: string;
  url: string;
  format?: string;
  deliveryMethod?: string;
  languageTag: string;
  displayLanguage: string;
  autoGenerated: boolean;
}

export interface StreamDetails {
  serviceId: number;
  url: string;
  name: string;
  uploaderName?: string;
  uploaderUrl?: string;
  uploaderAvatarUrl?: string;
  uploaderSubscriberCount?: number | null;
  thumbnailUrl?: string;
  duration: number;
  streamType: string;
  viewCount?: number | null;
  likeCount?: number | null;
  dislikeCount?: number | null;
  publishedAt?: number | null;
  textualUploadDate?: string;
  description?: string;
  descriptionType?: number;
  relatedItems: SearchItem[];
  dashMpdUrl?: string;
  hlsUrl?: string;
  videoStreams: StreamVariant[];
  audioStreams: StreamVariant[];
  subtitles: SubtitleVariant[];
  sponsorBlockSegments: SponsorBlockSegment[];
}

export type SponsorBlockCategoryId = 'sponsor' | 'intro' | 'outro' | 'interaction'
  | 'self_promo' | 'non_music' | 'preview' | 'filler' | 'highlight';
export type SponsorBlockBehavior = 'skip' | 'manual' | 'dont_skip';

export interface SponsorBlockSegment {
  uuid?: string;
  startTime: number;
  endTime: number;
  category: SponsorBlockCategoryId;
  action: 'skip' | 'poi';
}

export interface SponsorBlockCategoryPreference {
  enabled: boolean;
  behavior: SponsorBlockBehavior;
}

export interface SponsorBlockSettings {
  enabled: boolean;
  gracedRewind: boolean;
  notifications: boolean;
  categories: Record<SponsorBlockCategoryId, SponsorBlockCategoryPreference>;
}

export interface CommentItem {
  id?: string;
  text?: string;
  uploaderName?: string;
  uploaderAvatarUrl?: string;
  uploaderUrl?: string;
  publishedAt?: number | null;
  textualUploadDate?: string;
  likeCount?: number | null;
  textualLikeCount?: string;
  replyCount?: number | null;
  streamPosition?: number | null;
  uploaderVerified: boolean;
  heartedByUploader: boolean;
  pinned: boolean;
}

export interface StreamComments {
  disabled: boolean;
  items: CommentItem[];
}

export interface PlayerRequest {
  url: string;
  title?: string;
  audioUrl?: string;
  subtitleUrl?: string;
  startSeconds?: number;
}

export interface PlayerTrack {
  url: string;
  title?: string;
  language?: string;
}

export interface EmbeddedPlayerRequest {
  source: string;
  audio?: PlayerTrack;
  subtitle?: PlayerTrack;
  startSeconds?: number;
}

export interface PlayerStatus {
  embeddedAvailable: boolean;
  externalAvailable: boolean;
  executable?: string;
  running: boolean;
}

export type DownloadKind = 'video' | 'audio' | 'caption';
export type DownloadState = 'queued' | 'downloading' | 'muxing' | 'validating'
  | 'paused' | 'completed' | 'failed' | 'cancelled';

export type DownloadStage = 'queued' | 'downloading_video' | 'downloading_audio'
  | 'downloading_caption' | 'muxing' | 'validating' | 'paused' | 'completed' | 'failed' | 'cancelled';

export interface DownloadSource {
  url: string;
  kind?: DownloadKind;
  id?: string;
  format?: string;
  mimeType?: string;
  deliveryMethod?: string;
  resolution?: string;
  codec?: string;
  audioTrackId?: string;
  videoOnly?: boolean;
}

export interface DownloadComponent {
  role: DownloadKind;
  state: DownloadState;
  bytesDownloaded: number;
  totalBytes?: number;
}

export interface DownloadRequest {
  url?: string;
  sourceUrl: string;
  title: string;
  format?: string;
  mimeType?: string;
  kind?: DownloadKind;
  video?: DownloadSource;
  audio?: DownloadSource;
  caption?: DownloadSource;
}

export interface DownloadJob {
  id: string;
  title: string;
  fileName: string;
  kind: DownloadKind;
  state: DownloadState;
  stage: DownloadStage;
  bytesDownloaded: number;
  totalBytes?: number;
  createdAt: number;
  completedAt?: number;
  error?: string;
  outputContainer?: string;
  components: DownloadComponent[];
}

export interface LibraryStream {
  serviceId: number;
  url: string;
  title: string;
  duration: number;
  streamType: string;
  uploader?: string;
  uploaderUrl?: string;
  thumbnailUrl?: string;
}

export interface SubscriptionItem {
  serviceId: number;
  url: string;
  name: string;
  avatarUrl?: string;
  subscriberCount?: number | null;
  description?: string;
  youtubeModeMask?: number;
}

export interface ChannelDetails {
  serviceId: number;
  url: string;
  name: string;
  avatarUrl?: string;
  bannerUrl?: string;
  subscriberCount?: number | null;
  description?: string;
  streams: SearchItem[];
}

export interface PlaylistSummary {
  id: string;
  name: string;
  thumbnailUrl?: string;
  displayIndex: number;
  itemCount: number;
}

export interface PlaylistItem extends LibraryStream {
  itemId: string;
  position: number;
}

export interface HistoryItem extends LibraryStream {
  id: string;
  watchedAt: number;
  positionSeconds: number;
}

export interface SearchHistoryItem {
  id: string;
  serviceId: number;
  query: string;
  searchedAt: number;
}

export interface LearningNote extends LibraryStream {
  id: string;
  positionSeconds: number;
  note: string;
  createdAt: number;
  updatedAt: number;
}

export interface SyncStatus {
  protocol: string;
  peerId: string;
  listenAddresses: string[];
  trustedPeers: Array<{
    peerId: string;
    deviceName: string;
    lastSyncAtEpochMillis?: number;
    lastSyncError?: string;
    automaticRetry?: {
      consecutiveFailures: number;
      nextRetryAtEpochMillis?: number;
      lastAttemptAtEpochMillis?: number;
      lastOutcome?: SyncOutcome;
    };
  }>;
  dataSyncEnabled: boolean;
  automaticLanDiscovery: boolean;
  categories: string[];
  automaticPolicy: AutomaticSyncPolicy;
  automaticSchedule: {
    nextRunAtEpochMillis?: number;
    nextWakeAtEpochMillis?: number;
    lastAttemptAtEpochMillis?: number;
    lastOutcome?: SyncOutcome;
  };
  activeRun: {
    running: boolean;
    runId?: string;
    trigger?: SyncTrigger;
    startedAtEpochMillis?: number;
  };
  networkEligibility: {
    eligible: boolean;
    reason: 'privateLocalNetwork' | 'offlineOrNoPrivateNetwork';
  };
  lastRun?: SyncRunLog;
}

export type SyncTrigger = 'manual' | 'automatic';
export type SyncOutcome = 'running' | 'success' | 'partial' | 'failed'
  | 'skipped_offline' | 'skipped_busy' | 'skipped_no_devices' | 'skipped_backoff';

export interface AutomaticSyncPolicy {
  enabled: boolean;
  intervalMinutes: number;
  categories: string[];
  peerIds: string[];
  localNetworkOnly: true;
  updatedAtEpochMillis: number;
}

export interface SyncRunLog {
  runId: string;
  trigger: SyncTrigger;
  startedAtEpochMillis: number;
  completedAtEpochMillis?: number;
  outcome: SyncOutcome;
  requestedCategories: string[];
  requestedPeerIds: string[];
  succeeded: number;
  failed: number;
  error?: string;
  peers: Array<{
    peerId: string;
    deviceName: string;
    outcome: SyncOutcome;
    error?: string;
    results: Record<string, { sent?: number; received?: number; changed?: number; rounds?: number; error?: string }>;
  }>;
}

export interface SyncRunResult {
  requestedCategories: string[];
  succeeded: number;
  failed: number;
  peers: Array<{
    peerId: string;
    deviceName: string;
    error?: string;
    results: Record<string, { sent?: number; received?: number; changed?: number; rounds?: number; error?: string }>;
  }>;
}

export type UpdateStatus = 'unavailable' | 'idle' | 'checking' | 'up-to-date'
  | 'available' | 'downloading' | 'downloaded' | 'error';

export interface UpdateState {
  status: UpdateStatus;
  currentVersion: string;
  channel: 'beta';
  version?: string;
  releaseName?: string;
  releaseNotes?: string;
  percent?: number;
  checkedAt?: number;
  message?: string;
}

export type DesktopTheme = 'system' | 'light' | 'dark';
export type PreferredVideoFormat = 'video_mp4' | 'video_webm' | 'video_3gp';
export type PreferredAudioFormat = 'audio_m4a' | 'audio_webm';

export interface DesktopSettings {
  theme: DesktopTheme;
  defaultServiceId: number | null;
  defaultResolution: 'best_resolution' | '1080p60' | '1080p' | '720p60' | '720p'
    | '480p' | '360p' | '240p' | '144p';
  defaultVideoFormat: PreferredVideoFormat;
  defaultAudioFormat: PreferredAudioFormat;
  preferOriginalAudio: boolean;
  preferDescriptiveAudio: boolean;
  enableWatchHistory: boolean;
  enableSearchHistory: boolean;
  learningMode: boolean;
  learningNotes: boolean;
  sponsorBlock: SponsorBlockSettings;
}

export interface BackupOperationResult {
  cancelled?: boolean;
  status?: 'ready' | 'exported' | 'restored';
  fileName?: string;
  subscriptions?: number;
  playlists?: number;
  history?: number;
  searchHistory?: number;
  learningNotes?: number;
  settings?: DesktopSettings;
  imported?: number;
  exported?: number;
  source?: string;
}

export const defaultSponsorBlockSettings: SponsorBlockSettings = {
  enabled: false,
  gracedRewind: true,
  notifications: true,
  categories: {
    sponsor: { enabled: true, behavior: 'skip' },
    intro: { enabled: false, behavior: 'skip' },
    outro: { enabled: false, behavior: 'skip' },
    interaction: { enabled: false, behavior: 'skip' },
    self_promo: { enabled: false, behavior: 'skip' },
    non_music: { enabled: false, behavior: 'skip' },
    preview: { enabled: false, behavior: 'skip' },
    filler: { enabled: false, behavior: 'skip' },
    highlight: { enabled: false, behavior: 'dont_skip' },
  },
};

export const defaultDesktopSettings: DesktopSettings = {
  theme: 'system',
  defaultServiceId: null,
  defaultResolution: '720p60',
  defaultVideoFormat: 'video_mp4',
  defaultAudioFormat: 'audio_m4a',
  preferOriginalAudio: true,
  preferDescriptiveAudio: false,
  enableWatchHistory: true,
  enableSearchHistory: true,
  learningMode: false,
  learningNotes: true,
  sponsorBlock: defaultSponsorBlockSettings,
};

export interface DesktopApi {
  backend: {
    invoke<T>(method: BackendMethod, params?: Record<string, unknown>): Promise<T>;
  };
  player: {
    play(request: PlayerRequest): Promise<void>;
    stop(): Promise<void>;
    status(): Promise<PlayerStatus>;
  };
  downloads: {
    list(): Promise<DownloadJob[]>;
    start(request: DownloadRequest): Promise<DownloadJob>;
    pause(id: string): Promise<void>;
    resume(id: string): Promise<void>;
    cancel(id: string): Promise<void>;
    show(id: string): Promise<void>;
    openFolder(): Promise<void>;
    onChanged(listener: (jobs: DownloadJob[]) => void): () => void;
  };
  updates: {
    state(): Promise<UpdateState>;
    check(): Promise<UpdateState>;
    download(): Promise<UpdateState>;
    install(): Promise<void>;
    onChanged(listener: (state: UpdateState) => void): () => void;
  };
  settings: {
    get(): Promise<DesktopSettings>;
    update(patch: Partial<DesktopSettings>): Promise<DesktopSettings>;
    reset(): Promise<DesktopSettings>;
  };
  backup: {
    exportFull(): Promise<BackupOperationResult>;
    restoreFull(): Promise<BackupOperationResult>;
    importSubscriptions(): Promise<BackupOperationResult>;
    exportSubscriptions(): Promise<BackupOperationResult>;
  };
}

declare global {
  interface Window {
    wizestream: DesktopApi;
  }
}
