package org.wisso.wizestream.desktop.backend

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.schabi.newpipe.extractor.MediaFormat
import org.schabi.newpipe.extractor.ServiceList
import org.schabi.newpipe.extractor.stream.AudioStream
import org.schabi.newpipe.extractor.stream.AudioTrackType
import org.schabi.newpipe.extractor.stream.SubtitlesStream

class ExtractorFacadeTest {
    @Test
    fun `youtube search retains default content filter`() {
        val facade = ExtractorFacade()
        val handler = facade.createSearchQuery(ServiceList.YouTube, "mazen")

        assertTrue(handler.contentFilters.isNotEmpty())
        assertEquals("all", handler.contentFilters.first().name)
        ServiceList.YouTube.getSearchExtractor(handler)
    }

    @Test
    fun `audio variants retain language and semantic track labels`() {
        val stream = AudioStream.Builder()
            .setId("251")
            .setContent("https://media.example/audio.webm", true)
            .setMediaFormat(MediaFormat.WEBMA_OPUS)
            .setAverageBitrate(128)
            .setAudioTrackId("en.dubbed")
            .setAudioTrackName("English dubbed")
            .setAudioLocale("en-US")
            .setAudioTrackType(AudioTrackType.DUBBED)
            .build()

        val value = ExtractorFacade().audioStream(stream)

        assertEquals("en.dubbed", value["audioTrackId"])
        assertEquals("English dubbed", value["audioTrackName"])
        assertEquals("en-US", value["audioLocale"])
        assertEquals("DUBBED", value["audioTrackType"])
    }

    @Test
    fun `subtitle variants retain language and generated state`() {
        val stream = SubtitlesStream.Builder()
            .setId("ar.vtt")
            .setContent("https://media.example/captions.vtt", true)
            .setMediaFormat(MediaFormat.VTT)
            .setLanguageCode("ar-LB")
            .setAutoGenerated(true)
            .build()

        val value = ExtractorFacade().subtitleStream(stream)

        assertEquals("ar-LB", value["languageTag"])
        assertEquals(true, value["autoGenerated"])
    }
}
