package org.wisso.wizestream.desktop.backend

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import org.schabi.newpipe.extractor.MediaFormat
import org.schabi.newpipe.extractor.ServiceList
import org.schabi.newpipe.extractor.localization.DateWrapper
import org.schabi.newpipe.extractor.stream.AudioStream
import org.schabi.newpipe.extractor.stream.AudioTrackType
import org.schabi.newpipe.extractor.stream.StreamInfoItem
import org.schabi.newpipe.extractor.stream.StreamType
import org.schabi.newpipe.extractor.stream.SubtitlesStream
import java.time.OffsetDateTime
import java.time.ZoneOffset

class ExtractorFacadeTest {
    @Test
    fun `youtube search retains default content filter`() {
        val facade = ExtractorFacade()
        val handler = facade.createSearchQuery(ServiceList.YouTube, "mazen")

        assertTrue(handler.contentFilters.isNotEmpty())
        assertEquals("all", handler.contentFilters.first().name)
        ServiceList.YouTube.getSearchExtractor(handler)
    }

    @Test
    fun `audio variants retain language and semantic track labels`() {
        val stream = AudioStream.Builder()
            .setId("251")
            .setContent("https://media.example/audio.webm", true)
            .setMediaFormat(MediaFormat.WEBMA_OPUS)
            .setAverageBitrate(128)
            .setAudioTrackId("en.dubbed")
            .setAudioTrackName("English dubbed")
            .setAudioLocale("en-US")
            .setAudioTrackType(AudioTrackType.DUBBED)
            .build()

        val value = ExtractorFacade().audioStream(stream)

        assertEquals("en.dubbed", value["audioTrackId"])
        assertEquals("English dubbed", value["audioTrackName"])
        assertEquals("en-US", value["audioLocale"])
        assertEquals("DUBBED", value["audioTrackType"])
    }

    @Test
    fun `subtitle variants retain language and generated state`() {
        val stream = SubtitlesStream.Builder()
            .setId("ar.vtt")
            .setContent("https://media.example/captions.vtt", true)
            .setMediaFormat(MediaFormat.VTT)
            .setLanguageCode("ar-LB")
            .setAutoGenerated(true)
            .build()

        val value = ExtractorFacade().subtitleStream(stream)

        assertEquals("ar-LB", value["languageTag"])
        assertEquals(true, value["autoGenerated"])
    }

    @Test
    fun `feed items retain Android card metadata`() {
        val published = OffsetDateTime.of(2026, 8, 14, 12, 0, 0, 0, ZoneOffset.UTC)
        val item = StreamInfoItem(0, "https://video.example/watch/1", "Video", StreamType.VIDEO_STREAM).apply {
            uploaderName = "Channel"
            uploaderUrl = "https://video.example/channel"
            uploaderAvatarUrl = "https://video.example/avatar.png"
            duration = 600
            viewCount = 405_000
            uploadDate = DateWrapper(published)
            textualUploadDate = "10 hours ago"
            setShortFormContent(true)
        }

        val value = ExtractorFacade().searchItem(item)

        assertEquals("Channel", value["uploaderName"])
        assertEquals("https://video.example/avatar.png", value["uploaderAvatarUrl"])
        assertEquals(405_000L, value["viewCount"])
        assertEquals(published.toInstant().toEpochMilli(), value["publishedAt"])
        assertEquals("VIDEO_STREAM", value["streamType"])
        assertEquals(true, value["shortForm"])
    }

    @Test
    fun `empty subscription feed needs no network access`() {
        val feed = ExtractorFacade().subscriptionFeed(emptyList(), false)

        assertEquals(emptyList<Map<String, Any>>(), feed["items"])
        assertEquals(0, feed["totalChannels"])
        assertEquals(0, feed["failedChannels"])
    }
}
