/*
 * SPDX-FileCopyrightText: 2026 WizeStream contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

package org.schabi.newpipe.download

import java.util.stream.Stream
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertNull
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.Arguments
import org.junit.jupiter.params.provider.MethodSource
import org.schabi.newpipe.extractor.MediaFormat
import org.schabi.newpipe.extractor.stream.SubtitlesStream
import us.shandian.giga.postprocessing.Mp3OutputOptions

internal class DownloadOptionPoliciesTest {
    @ParameterizedTest
    @MethodSource("mediaSelections")
    fun `selects preferred available media with stable fallback order`(
        defaultMedia: String,
        videoAvailable: Boolean,
        audioAvailable: Boolean,
        subtitleAvailable: Boolean,
        expected: DownloadMediaOption?
    ) {
        assertEquals(
            expected,
            DownloadMediaOptionPolicy.select(
                defaultMedia,
                VIDEO_KEY,
                AUDIO_KEY,
                SUBTITLE_KEY,
                videoAvailable,
                audioAvailable,
                subtitleAvailable
            )
        )
    }

    @Test
    fun `returns no media option when no streams exist`() {
        assertNull(
            DownloadMediaOptionPolicy.select(
                VIDEO_KEY,
                VIDEO_KEY,
                AUDIO_KEY,
                SUBTITLE_KEY,
                videoAvailable = false,
                audioAvailable = false,
                subtitleAvailable = false
            )
        )
    }

    @Test
    fun `maps MP3 output and bitrate selections`() {
        assertFalse(DownloadAudioOutputPolicy.isMp3Output(0))
        assertTrue(DownloadAudioOutputPolicy.isMp3Output(1))
        assertEquals(128, DownloadAudioOutputPolicy.bitrateForIndex(0))
        assertEquals(320, DownloadAudioOutputPolicy.bitrateForIndex(3))
        assertEquals(
            Mp3OutputOptions.DEFAULT_BITRATE_KBPS,
            DownloadAudioOutputPolicy.bitrateForIndex(-1)
        )
        assertEquals(
            Mp3OutputOptions.DEFAULT_BITRATE_KBPS,
            DownloadAudioOutputPolicy.bitrateForIndex(4)
        )
    }

    @Test
    fun `shows bitrate only for a valid non-MP3 source`() {
        assertTrue(DownloadAudioOutputPolicy.shouldShowBitrate(1, 0, 1, MediaFormat.M4A))
        assertTrue(DownloadAudioOutputPolicy.shouldShowBitrate(1, 0, 1, null))
        assertFalse(DownloadAudioOutputPolicy.shouldShowBitrate(0, 0, 1, MediaFormat.M4A))
        assertFalse(DownloadAudioOutputPolicy.shouldShowBitrate(1, 1, 1, MediaFormat.M4A))
        assertFalse(DownloadAudioOutputPolicy.shouldShowBitrate(1, 0, 1, MediaFormat.MP3))
    }

    @Test
    fun `prefers exact subtitle locale over language fallback`() {
        val streams = listOf(subtitle("en-GB"), subtitle("en-US"), subtitle("fr-FR"))

        assertEquals(
            1,
            DownloadSubtitleSelectionPolicy.preferredIndex(streams, "en", "US")
        )
    }

    @Test
    fun `uses last matching subtitle language when country is unavailable`() {
        val streams = listOf(subtitle("en-GB"), subtitle("en-US"), subtitle("fr-FR"))

        assertEquals(
            1,
            DownloadSubtitleSelectionPolicy.preferredIndex(streams, "en", "CA")
        )
    }

    private fun subtitle(languageCode: String): SubtitlesStream {
        return SubtitlesStream.Builder()
            .setContent("https://example.com/$languageCode", true)
            .setMediaFormat(MediaFormat.SRT)
            .setLanguageCode(languageCode)
            .setAutoGenerated(false)
            .build()
    }

    private companion object {
        const val VIDEO_KEY = "video"
        const val AUDIO_KEY = "audio"
        const val SUBTITLE_KEY = "subtitle"

        @JvmStatic
        fun mediaSelections(): Stream<Arguments> = Stream.of(
            Arguments.of(
                AUDIO_KEY,
                true,
                true,
                true,
                DownloadMediaOption.AUDIO
            ),
            Arguments.of(
                AUDIO_KEY,
                true,
                false,
                true,
                DownloadMediaOption.VIDEO
            ),
            Arguments.of(
                VIDEO_KEY,
                false,
                true,
                true,
                DownloadMediaOption.AUDIO
            ),
            Arguments.of(
                VIDEO_KEY,
                false,
                false,
                true,
                DownloadMediaOption.SUBTITLE
            )
        )
    }
}
