/*
 * SPDX-FileCopyrightText: 2026 WizeStream contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

package org.schabi.newpipe.download

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertSame
import org.junit.jupiter.api.Test
import org.schabi.newpipe.extractor.MediaFormat
import org.schabi.newpipe.extractor.stream.AudioStream
import org.schabi.newpipe.extractor.stream.DeliveryMethod.PROGRESSIVE_HTTP
import org.schabi.newpipe.extractor.stream.Stream
import org.schabi.newpipe.extractor.stream.SubtitlesStream
import org.schabi.newpipe.extractor.stream.VideoStream

internal class DownloadStreamCatalogFactoryTest {
    @Test
    fun `prepared audio tracks and selections are retained`() {
        val audio = audio("en")
        val video = video("720", isVideoOnly = true)
        val subtitle = subtitle("en")

        val catalog = DownloadStreamCatalogFactory.fromPreparedStreams(
            context = null,
            groupedAudioStreams = listOf(listOf(audio)),
            videoStreams = listOf(video),
            subtitleStreams = listOf(subtitle),
            selectedAudioTrackIndex = 0,
            selectedVideoIndex = 0
        )

        assertSame(audio, catalog.audioTracks.tracksList.single().streamsList.single())
        assertSame(video, catalog.videoStreams.streamsList.single())
        assertSame(subtitle, catalog.subtitleStreams.streamsList.single())
        assertEquals(0, catalog.selectedAudioTrackIndex)
        assertEquals(0, catalog.selectedVideoIndex)
        assertEquals(-1, catalog.muxedAudioFallbackVideoIndex)
    }

    @Test
    fun `muxed video supplies audio only when no audio tracks exist`() {
        val muxedVideo = video("360", isVideoOnly = false)

        val catalog = DownloadStreamCatalogFactory.fromPreparedStreams(
            context = null,
            groupedAudioStreams = emptyList(),
            videoStreams = listOf(muxedVideo),
            subtitleStreams = emptyList(),
            selectedAudioTrackIndex = 0,
            selectedVideoIndex = 0
        )

        val fallbackAudio = catalog.audioTracks.tracksList.single().streamsList.single()
        assertEquals(0, catalog.muxedAudioFallbackVideoIndex)
        assertEquals("muxed-audio:360", fallbackAudio.id)
        assertEquals(muxedVideo.content, fallbackAudio.content)
        assertEquals(MediaFormat.M4A, fallbackAudio.format)
    }

    @Test
    fun `video-only catalog does not invent an audio fallback`() {
        val catalog = DownloadStreamCatalogFactory.fromPreparedStreams(
            context = null,
            groupedAudioStreams = emptyList(),
            videoStreams = listOf(video("360", isVideoOnly = true)),
            subtitleStreams = emptyList(),
            selectedAudioTrackIndex = -1,
            selectedVideoIndex = 0
        )

        assertEquals(0, catalog.audioTracks.size())
        assertEquals(-1, catalog.muxedAudioFallbackVideoIndex)
    }

    private fun audio(trackId: String): AudioStream {
        return AudioStream.Builder()
            .setId("audio-$trackId")
            .setContent("https://example.com/audio-$trackId", true)
            .setMediaFormat(MediaFormat.M4A)
            .setDeliveryMethod(PROGRESSIVE_HTTP)
            .setAverageBitrate(192)
            .setAudioTrackId(trackId)
            .build()
    }

    private fun video(id: String, isVideoOnly: Boolean): VideoStream {
        return VideoStream.Builder()
            .setId(id)
            .setContent("https://example.com/video-$id", true)
            .setMediaFormat(MediaFormat.MPEG_4)
            .setDeliveryMethod(PROGRESSIVE_HTTP)
            .setResolution("${id}p")
            .setIsVideoOnly(isVideoOnly)
            .build()
    }

    private fun subtitle(language: String): SubtitlesStream {
        return SubtitlesStream.Builder()
            .setContent("https://example.com/subtitle-$language", true)
            .setMediaFormat(MediaFormat.SRT)
            .setLanguageCode(language)
            .setAutoGenerated(false)
            .build()
    }
}
