package org.schabi.newpipe.player.resolver

import android.util.Base64
import androidx.media3.common.C
import androidx.media3.common.MediaItem
import androidx.media3.common.PlaybackException
import androidx.media3.common.Player
import androidx.media3.common.text.CueGroup
import androidx.media3.datasource.DefaultDataSource
import androidx.media3.exoplayer.ExoPlayer
import androidx.media3.exoplayer.source.MergingMediaSource
import androidx.media3.exoplayer.source.ProgressiveMediaSource
import androidx.media3.exoplayer.source.SingleSampleMediaSource
import androidx.test.platform.app.InstrumentationRegistry
import java.io.File
import java.util.concurrent.CountDownLatch
import java.util.concurrent.TimeUnit
import java.util.concurrent.atomic.AtomicReference
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import org.schabi.newpipe.extractor.MediaFormat
import org.schabi.newpipe.extractor.stream.DeliveryMethod
import org.schabi.newpipe.extractor.stream.SubtitlesStream
import org.schabi.newpipe.player.helper.CustomRenderersFactory
import org.schabi.newpipe.player.visualizer.VisualizerAudioProcessor

class SubtitlePlaybackSourceTest {
    private val instrumentation = InstrumentationRegistry.getInstrumentation()

    @Test
    fun inlineSrtAndTtmlReachThePlayerWithoutNetworkRequests() {
        val context = instrumentation.targetContext
        val video = File(context.cacheDir, "inline-subtitle-test.mp4")
        val encoded = instrumentation.context.assets.open("video-adjustments/red-sdr.mp4.base64").use { it.readBytes() }
        video.writeBytes(Base64.decode(encoded, Base64.DEFAULT))
        try {
            val samples = listOf(
                MediaFormat.SRT to "1\n00:00:00,000 --> 00:00:03,000\nHello مرحبا\n",
                MediaFormat.TTML to "<tt xmlns=\"http://www.w3.org/ns/ttml\"><body><div><p begin=\"0s\" end=\"3s\">Hello مرحبا</p></div></body></tt>"
            )
            for ((format, content) in samples) {
                val received = CountDownLatch(1)
                val error = AtomicReference<PlaybackException>()
                val text = AtomicReference<String>()
                var engine: ExoPlayer? = null
                try {
                    instrumentation.runOnMainSync {
                        val subtitle = SubtitlesStream.Builder()
                            .setContent(content, false)
                            .setMediaFormat(format)
                            .setLanguageCode("en")
                            .setAutoGenerated(false)
                            .build()
                        val remote = SingleSampleMediaSource.Factory {
                            throw AssertionError("Inline subtitles must not use the remote source")
                        }
                        val captions = requireNotNull(SubtitlePlaybackSource.create(subtitle, "en", remote))
                        val videoSource = ProgressiveMediaSource.Factory(DefaultDataSource.Factory(context))
                            .createMediaSource(MediaItem.fromUri(video.toURI().toString()))
                        engine = ExoPlayer.Builder(
                            context,
                            CustomRenderersFactory(context, false, VisualizerAudioProcessor())
                        ).build().apply {
                            trackSelectionParameters = trackSelectionParameters.buildUpon()
                                .setTrackTypeDisabled(C.TRACK_TYPE_VIDEO, true)
                                .setPreferredTextLanguage("en")
                                .build()
                            addListener(object : Player.Listener {
                                override fun onCues(cueGroup: CueGroup) {
                                    val value = cueGroup.cues.joinToString { it.text.toString() }
                                    if (value.contains("Hello")) {
                                        text.set(value)
                                        received.countDown()
                                    }
                                }

                                override fun onPlayerError(failure: PlaybackException) {
                                    error.set(failure)
                                    received.countDown()
                                }
                            })
                            setMediaSource(MergingMediaSource(videoSource, captions))
                            prepare()
                            play()
                        }
                    }
                    assertTrue("No caption callback for $format", received.await(20, TimeUnit.SECONDS))
                    assertNull(error.get())
                    assertTrue(text.get().orEmpty().contains("مرحبا"))
                } finally {
                    instrumentation.runOnMainSync { engine?.release() }
                }
            }
        } finally {
            video.delete()
        }
    }

    @Test
    fun unsupportedAndEmptySubtitlesAreIgnored() {
        val remote = SingleSampleMediaSource.Factory { throw AssertionError("Unexpected load") }
        for ((content, method) in listOf("" to DeliveryMethod.PROGRESSIVE_HTTP, "torrent" to DeliveryMethod.TORRENT)) {
            val subtitle = SubtitlesStream.Builder()
                .setContent(content, false)
                .setMediaFormat(MediaFormat.SRT)
                .setDeliveryMethod(method)
                .setLanguageCode("en")
                .setAutoGenerated(false)
                .build()
            assertNull(SubtitlePlaybackSource.create(subtitle, "en", remote))
        }
    }
}
