#!/usr/bin/env python3
"""Generate the bundled changelog from docs/changelogs.md (Python standard library only)."""

import argparse
import html
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "docs/changelogs.md"
TARGET = ROOT / "app/src/main/assets/changelog.html"
RELEASE = re.compile(r"## WizeStream ([^ ]+) \(`(\d+)`\)")
INLINE = re.compile(r"\[([^\]]+)\]\((https?://[^\s)]+)\)|\*\*(.+?)\*\*|`([^`]+)`")


def inline(text):
    pieces = []
    start = 0
    for match in INLINE.finditer(text):
        pieces.append(html.escape(text[start:match.start()]))
        if match[1] is not None:
            pieces.append(f'<a href="{html.escape(match[2], quote=True)}">{html.escape(match[1])}</a>')
        elif match[3] is not None:
            pieces.append(f"<strong>{html.escape(match[3])}</strong>")
        else:
            pieces.append(f"<code>{html.escape(match[4])}</code>")
        start = match.end()
    pieces.append(html.escape(text[start:]))
    return "".join(pieces)


def blocks(lines):
    output = []
    paragraph = []
    items = []

    def flush():
        if paragraph:
            output.append(f"<p>{inline(' '.join(paragraph))}</p>")
            paragraph.clear()
        if items:
            output.append("<ul>\n" + "\n".join(f"<li>{inline(item)}</li>" for item in items) + "\n</ul>")
            items.clear()

    for raw in lines:
        line = raw.strip()
        if not line:
            flush()
        elif line.startswith("### "):
            flush()
            output.append(f"<h3>{inline(line[4:])}</h3>")
        elif line.startswith("- "):
            if paragraph:
                flush()
            items.append(line[2:])
        elif line == "---":
            flush()
        elif raw.startswith("  ") and items:
            items[-1] += " " + line
        else:
            if items:
                flush()
            paragraph.append(line)
    flush()
    return "\n".join(output)


def generate(markdown):
    sections = []
    current = None
    for line in markdown.splitlines():
        release = RELEASE.fullmatch(line)
        if release or line == "## Unreleased":
            current = {"version": release[1] if release else None, "code": int(release[2]) if release else None, "lines": []}
            sections.append(current)
        elif current is not None:
            if line.startswith("## "):
                raise ValueError(f"Unrecognized changelog release heading: {line}")
            current["lines"].append(line)
    releases = [section for section in sections if section["code"] is not None]
    codes = [section["code"] for section in releases]
    if not codes or codes != sorted(set(codes), reverse=True):
        raise ValueError("Release version codes must be unique and newest first")
    config = (ROOT / "buildSrc/src/main/kotlin/ProjectConfig.kt").read_text(encoding="utf-8")
    parts = [int(re.search(rf"const val WIZESTREAM_VERSION_{part} = (\d+)", config)[1]) for part in ("MAJOR", "MINOR", "PATCH")]
    version = ".".join(map(str, parts))
    code = parts[0] * 1_000_000 + parts[1] * 1_000 + parts[2]
    if not any(section["version"] == version and section["code"] == code and blocks(section["lines"]) for section in releases):
        raise ValueError(f"Add release notes for WizeStream {version} ({code}) to {SOURCE.relative_to(ROOT)}")
    toc = []
    content = []
    for section in sections:
        body = blocks(section["lines"])
        if not body:
            continue
        version = section["version"]
        anchor = f"release-{section['code']}" if version else "unreleased"
        title = f"WizeStream {version}" if version else "Unreleased"
        attributes = f' data-version="{html.escape(version, quote=True)}" data-version-code="{section["code"]}"' if version else ""
        toc.append(f'<li><a href="#{anchor}">{html.escape(title)}</a></li>')
        content.append(f'<section id="{anchor}"{attributes}>\n<h2>{html.escape(title)}</h2>\n<div class="release-notes">\n{body}\n</div>\n</section>')
    return '''<!DOCTYPE html>
<!-- Generated by scripts/generate-changelog.py from docs/changelogs.md. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="color-scheme" content="light dark">
<title>WizeStream changelog</title>
<style>
:root { color-scheme: light dark; }
body { font-family: system-ui, sans-serif; line-height: 1.6; max-width: 54rem; margin: auto; padding: 1.25rem; overflow-wrap: anywhere; }
h1 { font-size: 1.75rem; } h2 { font-size: 1.4rem; } h3 { font-size: 1.1rem; }
section { margin-top: 2rem; padding-top: 1rem; border-top: 1px solid currentColor; }
li { margin-block: .45rem; } ul { padding-inline-start: 1.5rem; }
a { text-underline-offset: .15em; } summary { cursor: pointer; }
nav ul { columns: 2 14rem; } code { white-space: pre-wrap; }
</style>
</head>
<body>
<header><h1>WizeStream changelog</h1><p>Release history, newest first.</p></header>
<details><summary>Browse releases</summary><nav aria-label="Releases"><ul>
''' + "\n".join(toc) + '\n</ul></nav></details>\n<main>\n' + "\n".join(content) + '\n</main>\n</body>\n</html>\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the committed asset needs regeneration")
    args = parser.parse_args()
    generated = generate(SOURCE.read_text(encoding="utf-8"))
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != generated:
            sys.exit("Changelog asset is stale. Run: python3 scripts/generate-changelog.py")
        print("Bundled changelog matches docs/changelogs.md and the current release.")
    else:
        TARGET.write_text(generated, encoding="utf-8")
        print(f"Updated {TARGET.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
