allprojects {
    plugins.withId("com.android.application") {
        def androidComponents = extensions.getByName("androidComponents")

        androidComponents.finalizeDsl { androidExtension ->
            def releaseBuildType = androidExtension.buildTypes.getByName("release")

            if (androidExtension.buildTypes.findByName("nightly") == null) {
                androidExtension.buildTypes.create("nightly") {
                    initWith(releaseBuildType)
                    applicationIdSuffix ".nightly"
                    debuggable false
                    resValue "string", "app_name", "WizeStream Nightly"
                }
            }
        }
    }
}
