package org.schabi.newpipe.player.resolver;

import android.net.Uri;

import androidx.annotation.Nullable;
import androidx.media3.common.C;
import androidx.media3.common.MediaItem;
import androidx.media3.datasource.ByteArrayDataSource;
import androidx.media3.exoplayer.source.MediaSource;
import androidx.media3.exoplayer.source.SingleSampleMediaSource;

import org.schabi.newpipe.extractor.stream.DeliveryMethod;
import org.schabi.newpipe.extractor.stream.SubtitlesStream;

import java.nio.charset.StandardCharsets;

/** Preserves the extractor's distinction between subtitle URLs and inline UTF-8 text. */
final class SubtitlePlaybackSource {
    private SubtitlePlaybackSource() {
    }

    @Nullable
    static MediaSource create(final SubtitlesStream subtitle, final String language,
                              final SingleSampleMediaSource.Factory remoteFactory) {
        if (subtitle.getDeliveryMethod() == DeliveryMethod.TORRENT
                || subtitle.getFormat() == null || subtitle.getContent().isEmpty()) {
            return null;
        }
        final Uri uri;
        final SingleSampleMediaSource.Factory factory;
        if (subtitle.isUrl()) {
            uri = Uri.parse(subtitle.getContent());
            factory = remoteFactory;
        } else {
            // Keep caption text out of URLs, the network, and the shared media cache.
            uri = Uri.parse("wize-subtitle://inline");
            final byte[] content = subtitle.getContent().getBytes(StandardCharsets.UTF_8);
            factory = new SingleSampleMediaSource.Factory(() -> new ByteArrayDataSource(content));
        }
        final MediaItem.SubtitleConfiguration configuration =
                new MediaItem.SubtitleConfiguration.Builder(uri)
                        .setMimeType(subtitle.getFormat().getMimeType())
                        .setRoleFlags(subtitle.isAutoGenerated()
                                ? C.ROLE_FLAG_DESCRIBES_MUSIC_AND_SOUND : C.ROLE_FLAG_CAPTION)
                        .setLanguage(language)
                        .build();
        return factory.createMediaSource(configuration, C.TIME_UNSET);
    }
}
