package org.schabi.newpipe.extractor.services.youtube.extractors;

import com.grack.nanojson.JsonArray;
import com.grack.nanojson.JsonObject;

import org.schabi.newpipe.extractor.MediaFormat;
import org.schabi.newpipe.extractor.stream.SubtitlesStream;

import java.util.List;
import java.util.Locale;
import java.util.regex.Pattern;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

final class YoutubeCaptionTranslationHelper {
    private static final Pattern LANGUAGE_CODE_PATTERN = Pattern.compile(
            "^[A-Za-z]{2,3}(?:-[A-Za-z0-9]{2,8})*$");

    private YoutubeCaptionTranslationHelper() {
    }

    static void addTranslatedSubtitle(@Nonnull final List<SubtitlesStream> subtitles,
                                      @Nullable final JsonObject renderer,
                                      @Nonnull final MediaFormat format,
                                      @Nullable final String requestedLanguage) {
        if (renderer == null || renderer.isEmpty()) {
            return;
        }

        final JsonArray captions = renderer.getArray("captionTracks");
        if (captions == null || captions.isEmpty()) {
            return;
        }

        final String targetLanguage = resolveTranslationLanguage(
                renderer.getArray("translationLanguages"), requestedLanguage);
        if (targetLanguage == null || hasNativeCaption(captions, targetLanguage)) {
            return;
        }

        final JsonObject source = selectTranslatableSource(captions);
        if (source == null) {
            return;
        }

        final String url = buildCaptionUrl(
                source.getString("baseUrl"), format.getSuffix(), targetLanguage);
        if (url == null) {
            return;
        }

        subtitles.add(new SubtitlesStream.Builder()
                .setContent(url, true)
                .setMediaFormat(format)
                .setLanguageCode(targetLanguage)
                .setAutoGenerated(true)
                .build());
    }

    @Nullable
    static String normalizeLanguageCode(@Nullable final String languageCode) {
        if (languageCode == null) {
            return null;
        }

        final String normalized = languageCode.trim().replace('_', '-');
        return LANGUAGE_CODE_PATTERN.matcher(normalized).matches() ? normalized : null;
    }

    @Nullable
    static String resolveTranslationLanguage(@Nullable final JsonArray translationLanguages,
                                             @Nullable final String requestedLanguage) {
        final String normalizedRequested = normalizeLanguageCode(requestedLanguage);
        if (normalizedRequested == null) {
            return null;
        }

        if (translationLanguages == null || translationLanguages.isEmpty()) {
            return normalizedRequested;
        }

        for (int i = 0; i < translationLanguages.size(); i++) {
            final String candidate = normalizeLanguageCode(
                    translationLanguages.getObject(i).getString("languageCode"));
            if (candidate != null && candidate.equalsIgnoreCase(normalizedRequested)) {
                return candidate;
            }
        }

        final String requestedStem = languageStem(normalizedRequested);
        for (int i = 0; i < translationLanguages.size(); i++) {
            final String candidate = normalizeLanguageCode(
                    translationLanguages.getObject(i).getString("languageCode"));
            if (candidate != null && languageStem(candidate).equals(requestedStem)) {
                return candidate;
            }
        }

        return null;
    }

    static boolean hasNativeCaption(@Nonnull final JsonArray captions,
                                    @Nonnull final String targetLanguage) {
        for (int i = 0; i < captions.size(); i++) {
            final String captionLanguage = normalizeLanguageCode(
                    captions.getObject(i).getString("languageCode"));
            if (captionLanguage != null && languagesMatch(captionLanguage, targetLanguage)) {
                return true;
            }
        }
        return false;
    }

    @Nullable
    static JsonObject selectTranslatableSource(@Nonnull final JsonArray captions) {
        JsonObject generatedFallback = null;
        for (int i = 0; i < captions.size(); i++) {
            final JsonObject caption = captions.getObject(i);
            if (!caption.getBoolean("isTranslatable", true)
                    || isBlank(caption.getString("baseUrl"))
                    || isBlank(caption.getString("vssId"))
                    || isBlank(caption.getString("languageCode"))) {
                continue;
            }

            if (!caption.getString("vssId").startsWith("a.")) {
                return caption;
            }
            if (generatedFallback == null) {
                generatedFallback = caption;
            }
        }
        return generatedFallback;
    }

    @Nullable
    static String buildCaptionUrl(@Nullable final String baseUrl,
                                  @Nonnull final String formatSuffix,
                                  @Nonnull final String targetLanguage) {
        if (isBlank(baseUrl) || normalizeLanguageCode(targetLanguage) == null) {
            return null;
        }

        final int fragmentStart = baseUrl.indexOf('#');
        final String fragment = fragmentStart >= 0 ? baseUrl.substring(fragmentStart) : "";
        final String withoutFragment = fragmentStart >= 0
                ? baseUrl.substring(0, fragmentStart) : baseUrl;
        final int queryStart = withoutFragment.indexOf('?');
        final String path = queryStart >= 0
                ? withoutFragment.substring(0, queryStart) : withoutFragment;
        final String query = queryStart >= 0
                ? withoutFragment.substring(queryStart + 1) : "";

        final StringBuilder cleanQuery = new StringBuilder();
        for (final String part : query.split("&")) {
            if (part.isEmpty()) {
                continue;
            }
            final int equals = part.indexOf('=');
            final String name = equals >= 0 ? part.substring(0, equals) : part;
            if ("fmt".equals(name) || "tlang".equals(name)) {
                continue;
            }
            if (cleanQuery.length() > 0) {
                cleanQuery.append('&');
            }
            cleanQuery.append(part);
        }

        if (cleanQuery.length() > 0) {
            cleanQuery.append('&');
        }
        cleanQuery.append("fmt=").append(formatSuffix)
                .append("&tlang=").append(targetLanguage);
        return path + "?" + cleanQuery + fragment;
    }

    private static boolean languagesMatch(@Nonnull final String first,
                                          @Nonnull final String second) {
        if (first.equalsIgnoreCase(second)) {
            return true;
        }

        final String firstStem = languageStem(first);
        final String secondStem = languageStem(second);
        if (!firstStem.equals(secondStem)) {
            return false;
        }

        return !first.contains("-") || !second.contains("-") || "zh".equals(firstStem);
    }

    @Nonnull
    private static String languageStem(@Nonnull final String languageCode) {
        final String language = Locale.forLanguageTag(languageCode).getLanguage();
        return language.isEmpty()
                ? languageCode.split("-", 2)[0].toLowerCase(Locale.ROOT)
                : language.toLowerCase(Locale.ROOT);
    }

    private static boolean isBlank(@Nullable final String value) {
        return value == null || value.trim().isEmpty();
    }
}
